name: metalab-deploy-test

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    container: rocker/verse
    
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.2'
    - run: Rscript -e 'renv::restore()'
    - run: Rscript -e 'here::here("scripts", "main_builder.R")'

    