name: metalab-deploy-test

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.2'

    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev pandoc

    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Restore packages 
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()

    - run: Rscript -e 'source(here::here("scripts", "main_builder.R"))'
    - run: find ./shinyapps/* -type d -exec touch {}/restart.txt \;
    - run: cp -R metadata/ ./shinyapps/common/
    - run: cp -R data/ ./shinyapps/common/
    - run: tar -zcvf metalab-shinyapps.tar.gz shinyapps

    - run: Rscript -e 'source(here::here("scripts", "main_builder.R"))' -d

    - uses: actions/upload-artifact@v2
      with:
        name: metalab-shiny-apps
        path: ./metalab-shinyapps.tar.gz

    - name: scp shiny apps to staging server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "./shinyapps/*"
        target: "/srv/shiny-server-staging"
