name: metalab-deploy-test

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-deploy-staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.2'
    - run: Rscript -e 'print("MetaLab Build...")'
    